default_platform(:ios)

#
# Workaround for following error while executing `pod lib lint` and `pod trunk push`
#
# EXPANDED_CODE_SIGN_IDENTITY: unbound variable
# Command PhaseScriptExecution failed with a nonzero exit code
#
# For more information is available at
# https://github.com/CocoaPods/CocoaPods/issues/8000#issuecomment-434488071
#
ENV["EXPANDED_CODE_SIGN_IDENTITY"] = ""
ENV["EXPANDED_CODE_SIGN_IDENTITY_NAME"] = ""
ENV["EXPANDED_PROVISIONING_PROFILE"] = ""

default_xcodeproj = "Punycode.xcodeproj"

platform :ios do

    desc "Run Tests"
    lane :tests do
        xcclean
        run_tests(
            scheme: "Punycode-iOS",
            devices: ["iPhone X"]
        )
        run_tests(
            scheme: "Punycode-macOS",
            destination: "platform=macOS"
        )
        run_tests(
            scheme: "Punycode-tvOS",
            devices: ["Apple TV"]
        )
    end

    desc "Build Carthage"
    lane :build_carthage do |options|
        carthage(
            command: "build",
            verbose: true,
            no_skip_current: true
        )
    end

    desc "Lint Cocoapods"
    lane :lint_cocoapods do |options|
        pod_lib_lint(verbose: true)
    end

    desc "Push Cocoapods"
    lane :push_cocoapods do |options|
        pod_lib_lint(verbose: true)
        pod_push(path: "Punycode.podspec")
    end

    desc "Upgrade version number"
    lane :version do
        bump_type = UI.select("Select version position to be upgraded: ", ["patch", "minor", "major"])
        if ["patch", "minor", "major"].include?(bump_type) then
            version = increment_version_number(bump_type: bump_type)
        end
        increment_build_number(build_number: create_new_build_number)
    end

    def create_new_build_number
        # Current Version Number
        current_version_number = get_version_number(xcodeproj: $default_xcodeproj)
        # New Build Number
        new_build = Time.now.strftime("%Y%m%d%H%M")
        new_build_number = current_version_number + "." + new_build
        return new_build_number
    end
end
